# -*- coding: utf-8 -*-
"""02_download_metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eqEn8vkMvxB4C8N0bjf2xXHEecKpfeTG

#Extraer el texto de Tik Tok

##1 — Instalar dependencias
"""

TIKTOK_URL = "https://vt.tiktok.com/ZSataVEaX/"
#"https://vt.tiktok.com/ZSatjpvbJ/"
OUT_DIR = "/content/tiktok"

!pip -q install -U yt-dlp requests

"""##2 — Extraer metadata del video (yt-dlp JSON)"""

import os, json
import yt_dlp

os.makedirs(OUT_DIR, exist_ok=True)

ydl_opts = {
    "quiet": True,
    "no_warnings": True,
    "noplaylist": True,
}

with yt_dlp.YoutubeDL(ydl_opts) as ydl:
    info = ydl.extract_info(TIKTOK_URL, download=False)

raw_path = f"{OUT_DIR}/video_info_raw.json"
with open(raw_path, "w", encoding="utf-8") as f:
    json.dump(info, f, ensure_ascii=False, indent=2)

print("RAW guardado:", raw_path)
print("Keys ejemplo:", list(info.keys())[:30])

"""##3 — Parsear: música, track, artista, cuenta"""

def pick(*vals):
    for v in vals:
        if v not in (None, "", "NA"):
            return v
    return None

uploader = pick(info.get("uploader"), info.get("channel"), info.get("creator"))
uploader_id = pick(info.get("uploader_id"), info.get("channel_id"))
uploader_url = pick(info.get("uploader_url"), info.get("channel_url"), info.get("webpage_url_basename"))

track = pick(info.get("track"), info.get("alt_title"))
artist = pick(info.get("artist"), info.get("composer"))
# En muchos casos TikTok pone "original sound" sin artista; igual cuenta como audio/sonido.
has_music = bool(track or artist)

meta = {
    "tiktok_url": TIKTOK_URL,
    "id": info.get("id"),
    "title": info.get("title"),
    "duration_sec": info.get("duration"),
    "uploader_name": uploader,
    "uploader_id": uploader_id,
    "uploader_url": uploader_url,
    "has_music": has_music,
    "track": track,
    "artist": artist,
    "view_count": info.get("view_count"),
    "like_count": info.get("like_count"),
    "comment_count": info.get("comment_count"),
    "repost_count": info.get("repost_count"),
}

meta

"""##4 — Intentar followers/seguidos desde el perfil (scraping “best effort”)

Esto puede fallar si TikTok bloquea la petición desde Colab. Si falla, igual dejamos todo lo demás OK.
"""

import re, requests

def fetch_profile_stats(unique_id: str):
    if not unique_id:
        return {"followers": None, "following": None, "profile_name": None, "status": "no_uploader"}

    url = f"https://www.tiktok.com/@{unique_id}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Accept-Language": "es-CL,es;q=0.9,en;q=0.8",
        "Referer": "https://www.tiktok.com/",
    }

    r = requests.get(url, headers=headers, timeout=20)
    if r.status_code != 200:
        return {"followers": None, "following": None, "profile_name": None, "status": f"http_{r.status_code}"}

    html = r.text

    # Busca followerCount/followingCount (aparecen en JSON embebido en la página)
    m_followers = re.search(r'"followerCount"\s*:\s*(\d+)', html)
    m_following = re.search(r'"followingCount"\s*:\s*(\d+)', html)
    m_nickname  = re.search(r'"nickname"\s*:\s*"([^"]+)"', html)

    return {
        "followers": int(m_followers.group(1)) if m_followers else None,
        "following": int(m_following.group(1)) if m_following else None,
        "profile_name": m_nickname.group(1) if m_nickname else None,
        "status": "ok" if (m_followers or m_following) else "parsed_none"
    }

# OJO: a veces uploader_id no es el @handle. Si uploader_url trae "@handle", lo extraemos.
unique_id_guess = None
if isinstance(uploader_url, str) and "@" in uploader_url:
    unique_id_guess = uploader_url.split("@")[-1].split("/")[0]
elif isinstance(uploader, str) and " " not in uploader and len(uploader) <= 40:
    unique_id_guess = uploader  # fallback

profile = fetch_profile_stats(unique_id_guess)
profile

"""##5 — Unir todo y guardar metadata.json"""

import json

final = {**meta, **{
    "profile_unique_id_guess": unique_id_guess,
    "profile_name": profile.get("profile_name"),
    "followers": profile.get("followers"),
    "following": profile.get("following"),
    "profile_status": profile.get("status"),
}}

out_path = f"{OUT_DIR}/metadata.json"
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(final, f, ensure_ascii=False, indent=2)

print("✅ Guardado:", out_path)
final

"""###A) Mejorar la transcripción (rápido)
####1) Ver timestamps y segmentos (para validar)
"""

import json

with open("/content/tiktok/segments.json", "r", encoding="utf-8") as f:
    segs = json.load(f)

for s in segs[:10]:
    print(f"[{s['start']:.2f}–{s['end']:.2f}] {s['text']}")

"""⛳ Esto te permite ver si “Cuando falla la Matrix.” está bien capturado o se comió contexto.

### Para guardar los substitulos
Ahora se guarda la información en el laptop
"""

!whisper "/content/tiktok/audio.wav" --model small --language es --output_dir "/content/tiktok" --output_format srt
!ls -la /content/tiktok/*.srt

"""se descarga la info"""

from google.colab import files
files.download("/content/tiktok/transcripcion.txt")
files.download("/content/tiktok/segments.json")